### ISSUE TITLE
Crash when the library is used along with wdullaer/MaterialDateTimePicker

### ISSUE THREAD

**Issue by ragunathjawahar** [borax12/MaterialDateRangePicker#45]
``` java
Fatal Exception: java.lang.ClassCastException: com.wdullaer.materialdatetimepicker.date.AccessibleDateAnimator cannot be cast to com.borax12.materialdaterangepicker.date.AccessibleDateAnimator
       at com.borax12.materialdaterangepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:371)
       at android.app.Fragment.performCreateView(Fragment.java:2114)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
       at android.app.BackStackRecord.run(BackStackRecord.java:834)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1469)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by yingzhox** [comment]
I met the same issue, any solutions?

**Comment by wdullaer** [comment]
As both libraries use the same names for various things, you're going to have to cast using the full namespaced class names in your code if you use both at the same time.

**Comment by heysupratim** [comment]
if you are using both the the libraries , then a full namespace resolution for all methods will have to be done , for example - com.borax12.materialdaterangepicker.date.DatePickerDialog.newInstance(.....) instead of just DatePickerDialog.newInstance(....)

**Comment by meddd** [comment]
it dosn work. still i got errot
 at com.borax12.materialdaterangepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:399)

**Comment by RamithRD** [comment]
I can confirm the issue still persists.
` java.lang.NoSuchFieldError: No static field hours of type I in class Lcom/borax12/materialdaterangepicker/R$id; or its superclasses (declaration of 'com.borax12.materialdaterangepicker.R$id' appears in /data/app/com.example.ramithrd.lecturemanagementsystem-2/split_lib_slice_4_apk.apk)
                                                                                                  at com.borax12.materialdaterangepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:336)
                                                                                                  at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                                                  at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

**Comment by thomas-ostrowski** [comment]
I had the same error.
`java.lang.NoSuchFieldError: No static field date_picker_header of type I in class Lcom/borax12/materialdaterangepicker/R$id; or its superclasses (declaration of 'com.borax12.materialdaterangepicker.R$id' appears in /data/app/my-app-package-1/split_lib_slice_9_apk.apk) at com.borax12.materialdaterangepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:336) at android.app.Fragment.performCreateView(Fragment.java:2220)`
Any known workaround ?

**Comment by sarah1230** [comment]
java.lang.NoSuchFieldError: com.borax12.materialdaterangepicker.R$id.date_picker_header
                                                                               at com.borax12.materialdaterangepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:336)
                                                                               at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)

 the same error

**Comment by wdullaer** [comment]
Are you sure you're using the latest version of MaterialDateTimePicker?
I prefixed all ids a while back, to avoid these type of conflicts.

**Comment by vit001** [comment]
This crash still exists with the latest version of MaterialDateTimePicker.

**Comment by suchoX** [comment]
The issue still exists!

**Comment by arnavdots** [comment]
any luck on this, facing same issue

**Comment by erlangparasu** [comment]
facing same issue

**Comment by ghost** [comment]
Hi,i found the problem and solved it, if u use both library "material time picker" and "material date range picker" together,It doesn't work because both library xml files Have the same name.u should add materialDateRangePicker to your project as a module and refactor->rename all the xml files and rebuild and run.its working

**Comment by erlangparasu** [comment]
thanks @atefeh-srch :+1:
